create table if not exists public.rs_media_analytics_events (
  id bigint generated by default as identity primary key,
  module text not null check (module in ('broadcast','radio','stream','rs_ads')),
  event_type text not null check (event_type in ('upload_submitted','published','play_start','play_heartbeat','play_complete','ad_created','ad_impression','ad_click','payment_started','payment_paid','payment_failed','refund','review_rejected')),
  content_id text,
  campaign_id text,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  device_type text,
  country_code text,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  amount numeric(12,2) not null default 0 check (amount >= 0),
  currency text not null default 'EUR',
  provider text,
  payment_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists rs_media_analytics_module_event_created_idx on public.rs_media_analytics_events(module, event_type, created_at desc);
create index if not exists rs_media_analytics_content_idx on public.rs_media_analytics_events(content_id, created_at desc);
create index if not exists rs_media_analytics_campaign_idx on public.rs_media_analytics_events(campaign_id, created_at desc);
create index if not exists rs_media_analytics_user_idx on public.rs_media_analytics_events(user_id, created_at desc);
alter table public.rs_media_analytics_events enable row level security;
drop policy if exists "CEO reads media analytics" on public.rs_media_analytics_events;
create policy "CEO reads media analytics" on public.rs_media_analytics_events for select to authenticated using (exists (select 1 from public.rs_admin_roles r where r.user_id = auth.uid() and r.role = 'admin'));
drop policy if exists "Users insert own media analytics" on public.rs_media_analytics_events;
create policy "Users insert own media analytics" on public.rs_media_analytics_events for insert to authenticated with check (user_id = auth.uid() or user_id is null);
